site_name: NERVA Docs
site_url: https://docs.nerva.one
repo_url: https://github.com/nerva-project/nerva-docs
site_description: Official NERVA documentation
edit_uri: blob/master/docs/
theme:
    name: null
    custom_dir: 'nerva-docs-theme/mkdocs_bootstrap4/'
    suppress_nextprev: true
extra_css: [nerva.css]
copyright: "&copy; 2018 - 2026 <strong>The Nerva Project</strong>"
nav:
    - About: 'about.md'
    - User Guides:
        - 'CLI Guide': 'guides/cli.md'
        - 'GUI Guide': 'guides/gui.md'
        - 'Docker Guide': 'guides/docker.md'
        - 'Mining FAQ': 'guides/mining.md'
        - 'Tor Guide' : 'guides/tor.md'
        - 'Multisig Guide': 'guides/multisig.md'
        - 'Ledger Hardware Wallet': 'guides/ledger.md'
    - Developer:
        - 'Developer Guide': 'guides/develop.md'
        - 'Daemon RPC': 'developer/daemon-rpc.md'
        - 'Wallet RPC': 'developer/wallet-rpc.md'
        - 'Building From Source': 'developer/building-from-source.md'
    - Community Projects: 'projects.md'
plugins:
    - git-committers:
        repository: nerva-project/nerva-docs
        branch: master
        token: !!python/object/apply:os.getenv ["MKDOCS_GIT_COMMITTERS_APIKEY"]
    - search
